// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearUserOTP = `-- name: ClearUserOTP :exec
UPDATE users
SET reset_token = NULL, reset_token_expiry = NULL
WHERE id = $1
`

func (q *Queries) ClearUserOTP(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearUserOTP, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, phone_number, role)
VALUES ($1, $2, $3)
RETURNING id, name, phone_number, role, created_at
`

type CreateUserParams struct {
	Name        string
	PhoneNumber string
	Role        Roles
}

type CreateUserRow struct {
	ID          pgtype.UUID
	Name        string
	PhoneNumber string
	Role        Roles
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.PhoneNumber, arg.Role)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, phone_number, role, reset_token, reset_token_expiry, created_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Role,
		&i.ResetToken,
		&i.ResetTokenExpiry,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByPhoneNumber = `-- name: GetUserByPhoneNumber :one
SELECT id, name, phone_number, role, reset_token, reset_token_expiry, created_at
FROM users
WHERE phone_number = $1
LIMIT 1
`

func (q *Queries) GetUserByPhoneNumber(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhoneNumber, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Role,
		&i.ResetToken,
		&i.ResetTokenExpiry,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, phone_number, role, created_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

type ListUsersRow struct {
	ID          pgtype.UUID
	Name        string
	PhoneNumber string
	Role        Roles
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PhoneNumber,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserOTP = `-- name: UpdateUserOTP :exec
UPDATE users
SET reset_token = $2, reset_token_expiry = $3
WHERE phone_number = $1
`

type UpdateUserOTPParams struct {
	PhoneNumber      string
	ResetToken       *string
	ResetTokenExpiry pgtype.Timestamptz
}

func (q *Queries) UpdateUserOTP(ctx context.Context, arg UpdateUserOTPParams) error {
	_, err := q.db.Exec(ctx, updateUserOTP, arg.PhoneNumber, arg.ResetToken, arg.ResetTokenExpiry)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users
SET role = $2
WHERE phone_number = $1
`

type UpdateUserRoleParams struct {
	PhoneNumber string
	Role        Roles
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.PhoneNumber, arg.Role)
	return err
}
